server.port==${PORT:8080}

spring.datasource.url=jdbc:mysql://fsad-project-backend-production-36a0.up.railway.app?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=EZNIaDiIAyTWVtpQOgvkLRvDMKecmqzO
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.open-in-view=false
